package rokefeli.ui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import rokefeli.logic.GestorInventario;

public class DatosVenta extends javax.swing.JDialog {

    private boolean confirmado = false;
    
    /**
     * Creates new form DatosVenta
     */
    public DatosVenta(java.awt.Frame parent, String[] productosDisponibles) {
        super(parent, "Registrar Venta", true);
        // 1. Llamamos a initComponents 
        initComponents(); 

        // 2. Primero, verificamos si hay productos. Si no hay, mostramos el mensaje y cerramos el diálogo.
        if (productosDisponibles == null || productosDisponibles.length == 0) {
            JOptionPane.showMessageDialog(parent,
                    "No hay productos con stock disponibles para la venta.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
            dispose(); // Cierra el diálogo si no hay productos
            return; // Salir del constructor
        }
        
        // 3. Si hay productos, poblar el JComboBox utilizando su MODELO.
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(productosDisponibles);
        cbxProductos.setModel(model); // <--- ESTA ES LA LÍNEA CORRECTA PARA POBLAR EL JCOMBOBOX EXISTENTE
        
        // Configurar la fecha actual y hacerla no editable
        txtFecha.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        txtFecha.setEditable(false);

        // Puedes configurar el primer elemento seleccionado si lo deseas
        if (productosDisponibles.length > 0) {
            cbxProductos.setSelectedIndex(0);
        }

        // Configuración de tamaño, posición, y operación de cierre
        pack(); // Ajusta el tamaño de la ventana a sus componentes
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    private boolean validarCampos() {
        if (txtComprador.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del comprador no puede estar vacío.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {
            int cantidad = Integer.parseInt(txtCantidad.getText().trim());
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser un número positivo.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    // Getters para que la interfaz principal pueda recuperar los datos
    public boolean isConfirmado() { return confirmado; }
    public String getProductoSeleccionado() { return (String) cbxProductos.getSelectedItem(); }
    public int getCantidad() { return Integer.parseInt(txtCantidad.getText().trim()); }
    public String getComprador() { return txtComprador.getText().trim(); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxProductos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtComprador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnVender = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Producto a Vender:");
        getContentPane().add(jLabel1);

        cbxProductos.setBackground(new java.awt.Color(255, 204, 51));
        cbxProductos.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cbxProductos.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(cbxProductos);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2);

        txtCantidad.setBackground(new java.awt.Color(255, 204, 51));
        txtCantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCantidad);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Comprador:");
        getContentPane().add(jLabel3);

        txtComprador.setBackground(new java.awt.Color(255, 204, 51));
        txtComprador.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtComprador.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtComprador);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha de Venta:");
        getContentPane().add(jLabel4);

        txtFecha.setBackground(new java.awt.Color(255, 204, 51));
        txtFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtFecha);

        btnVender.setBackground(new java.awt.Color(255, 255, 255));
        btnVender.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnVender.setForeground(new java.awt.Color(0, 0, 0));
        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        getContentPane().add(btnVender);

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        if (validarCampos()) {
                confirmado = true;
                dispose();
            }
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // *** Para propósito de prueba aislada del diálogo ***
                // Simula datos de productos disponibles
                String[] productosParaPrueba = {"Frasco 1kg", "Frasco 1/2kg", "Bolsa 1kg"};
                DatosVenta dialog = new DatosVenta(new javax.swing.JFrame(), productosParaPrueba);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cbxProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtComprador;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
