package rokefeli.ui;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import rokefeli.model.LoteMielCosecha;

public class DatosLoteMiel extends javax.swing.JDialog {

    private LoteMielCosecha nuevoLote;
    
    public LoteMielCosecha getLoteMielCosecha(){
        return nuevoLote;
    }
    
    public DatosLoteMiel(java.awt.Frame parent) {
        super(parent, "Registrar Lote de Miel", true);
        initComponents();
        setSize(600, 250);
        txtFechaIngreso.setText(LocalDate.now().toString());
        setLocationRelativeTo(parent); // Centrar sobre el padre
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Cerrar solo este di�logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxFloracion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnGuardarLoteMiel = new javax.swing.JButton();
        btnCancelarLoteMiel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Floración:");
        getContentPane().add(jLabel1);

        cbxFloracion.setBackground(new java.awt.Color(255, 204, 51));
        cbxFloracion.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cbxFloracion.setForeground(new java.awt.Color(0, 0, 0));
        cbxFloracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Huarango", "Eucalipto", "Naranjo", "Polifloral (S)", "Polifloral (C)" }));
        getContentPane().add(cbxFloracion);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Origen:");
        getContentPane().add(jLabel2);

        txtOrigen.setBackground(new java.awt.Color(255, 204, 51));
        txtOrigen.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtOrigen.setForeground(new java.awt.Color(0, 0, 0));
        txtOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigenActionPerformed(evt);
            }
        });
        getContentPane().add(txtOrigen);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de Ingreso:");
        getContentPane().add(jLabel3);

        txtFechaIngreso.setBackground(new java.awt.Color(255, 204, 51));
        txtFechaIngreso.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtFechaIngreso.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtFechaIngreso);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cantidad (kg):");
        getContentPane().add(jLabel4);

        txtCantidad.setBackground(new java.awt.Color(255, 204, 51));
        txtCantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCantidad);

        btnGuardarLoteMiel.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarLoteMiel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnGuardarLoteMiel.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarLoteMiel.setText("Guardar");
        btnGuardarLoteMiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLoteMielActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarLoteMiel);

        btnCancelarLoteMiel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarLoteMiel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCancelarLoteMiel.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarLoteMiel.setText("Cancelar");
        btnCancelarLoteMiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLoteMielActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarLoteMiel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigenActionPerformed

    private void btnGuardarLoteMielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLoteMielActionPerformed
        String floracion = cbxFloracion.getSelectedItem().toString();
        String origen = txtOrigen.getText();
        
        if(floracion.trim().isEmpty() || origen.trim().isEmpty() || txtCantidad.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Uno o más campos vacíos, por favor rellene todo para continuar.");
        } else{
            try{
                double cant = Double.parseDouble(txtCantidad.getText());
                if (cant <= 0) {
                    JOptionPane.showMessageDialog(this, "La cantidad debe ser un número positivo.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                    return;
                } else{
                    nuevoLote = new LoteMielCosecha(null, floracion, origen, LocalDate.now(), cant);
                    dispose();
                }
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Valor no válido en el campo 'Cantidad'", "Error de entrada", JOptionPane.ERROR_MESSAGE);
                txtCantidad.setText("");
                txtCantidad.requestFocus();
            }
        }
    }//GEN-LAST:event_btnGuardarLoteMielActionPerformed

    private void btnCancelarLoteMielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLoteMielActionPerformed
        nuevoLote = null;
        dispose();
    }//GEN-LAST:event_btnCancelarLoteMielActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosLoteMiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosLoteMiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosLoteMiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosLoteMiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DatosLoteMiel dialog = new DatosLoteMiel(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarLoteMiel;
    private javax.swing.JButton btnGuardarLoteMiel;
    private javax.swing.JComboBox<String> cbxFloracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
