package rokefeli.ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import rokefeli.logic.GestorInventario; 

public class DatosProductoFinal extends javax.swing.JDialog {
    
    private boolean confirmado = false;
    
    /**
     * Creates new form DatosProductoFinal
     */
    public DatosProductoFinal(java.awt.Frame parent, String[] idsLotes) {
        super(parent, "Crear Producto Final", true);
        initComponents();
        // Primero, verificamos si hay lotes. Si no hay, mostramos el mensaje y nos vamos.
        if (idsLotes == null || idsLotes.length == 0) {
            JOptionPane.showMessageDialog(parent,
                    "No hay lotes de miel en estado 'Lista para Envasar'.\n" +
                    "Por favor, transforme un lote primero.",
                    "Acción Requerida",
                    JOptionPane.INFORMATION_MESSAGE);
            // Si no hay lotes, dispose() cierra el diálogo.
            dispose(); 
            return; // Salir del constructor si no hay lotes.
        }
        // Si hay lotes, poblar el JComboBox.
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(idsLotes);
        cbxLotes.setModel(model);

        if (idsLotes.length > 0) {
            cbxLotes.setSelectedIndex(0);
        }
        
        // Configuración de tamaño, posición, y operación de cierre
        pack(); // Ajusta el tamaño al contenido
        setLocationRelativeTo(parent); // Centrar sobre el padre
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Cerrar solo este diálogo
    }
    
    private boolean validarCampos() {
        if (" ".equals(cbxTipoProducto.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de producto.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        String cantTexto = txtCantidad.getText();
        if (cantTexto.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo 'Cantidad' no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        try {
            int cantidad = Integer.parseInt(cantTexto);
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser un número positivo.", "Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido en 'Cantidad'.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    public String getIdLoteSeleccionado() {
        return (String) cbxLotes.getSelectedItem();
    }
    public String getTipoProductoSeleccionado() {
        return (String) cbxTipoProducto.getSelectedItem();
    }
    public int getCantidad() {
        return Integer.parseInt(txtCantidad.getText());
    }
    public boolean isConfirmado() {
        return confirmado;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxLotes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxTipoProducto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lote de Miel a usar:");
        getContentPane().add(jLabel1);

        cbxLotes.setBackground(new java.awt.Color(255, 204, 51));
        cbxLotes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        getContentPane().add(cbxLotes);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tipo de Producto a crear:");
        getContentPane().add(jLabel2);

        cbxTipoProducto.setBackground(new java.awt.Color(255, 204, 51));
        cbxTipoProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cbxTipoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Miel Frasco 1kg (vidrio)", "Miel Frasco 1/2kg (vidrio)", "Miel Frasco 1kg (plástico)", "Miel Frasco 1/2kg (plástico)", "Miel Bolsa 1kg", "Miel Bolsa 1/2kg" }));
        getContentPane().add(cbxTipoProducto);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cantidad de unidades a crear:");
        getContentPane().add(jLabel3);

        txtCantidad.setBackground(new java.awt.Color(255, 204, 51));
        txtCantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        getContentPane().add(txtCantidad);

        btnCrear.setBackground(new java.awt.Color(255, 255, 255));
        btnCrear.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(0, 0, 0));
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear);

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (validarCampos()) {
            confirmado = true;
            dispose();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosProductoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosProductoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosProductoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosProductoFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestorInventario dummyGestor = new GestorInventario();
                dummyGestor.cargarInventario();
                if (dummyGestor.getIdsLotesListosParaEnvasar().length == 0) {
                    dummyGestor.inventarioMateriaPrima.add(new rokefeli.model.MateriaPrima("LOTE_TEST_01", "Polifloral", "Granja Demo", LocalDate.now(), 50.0));
                    dummyGestor.inventarioMateriaPrima.get(0).setEstado("Lista para Envasar");
                    dummyGestor.inventarioMateriaPrima.add(new rokefeli.model.MateriaPrima("LOTE_TEST_02", "Eucalipto", "Granja Demo", LocalDate.now(), 30.0));
                    dummyGestor.inventarioMateriaPrima.get(1).setEstado("Lista para Envasar");
                }
                
                // Obtener los IDs de lotes listos para envasar del GestorInventario dummy
                String[] idsLotesParaPrueba = dummyGestor.getIdsLotesListosParaEnvasar();

                DatosProductoFinal dialog = new DatosProductoFinal(new javax.swing.JFrame(), idsLotesParaPrueba);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> cbxLotes;
    private javax.swing.JComboBox<String> cbxTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
