/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rokefeli.ui;

import javax.swing.JOptionPane;


public class DatosInsumo extends javax.swing.JDialog {
    
    int cantidad;
    String tipoInsumo;
    
    public int getCantidad(){
        return cantidad;
    }
    
    public String getTipoInsumo(){
        return tipoInsumo;
    }
    
    
    /**
     * Creates new form DatosInsumo
     */
    public DatosInsumo(java.awt.Frame parent) {
        super(parent, "Registrar Lote de Miel", true);
        initComponents();
        setSize(600, 250);
        setLocationRelativeTo(parent); // Centrar sobre el padre
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Cerrar solo este di�logo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxInsumo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadInsumo = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Insumo:");
        getContentPane().add(jLabel1);

        cbxInsumo.setBackground(new java.awt.Color(255, 204, 51));
        cbxInsumo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cbxInsumo.setForeground(new java.awt.Color(0, 0, 0));
        cbxInsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Frasco 1kg (plástico)", "Frasco 1kg (vidrio)", "Frasco 1/2kg (plástico)", "Frasco 1/2kg (vidrio)", "Bolsa 1kg", "Bolsa 1/2kg", "Precinto 1kg", "Precinto 1/2kg", "Etiqueta Frasco 1kg", "Etiqueta Frasco 1/2kg", "Etiqueta Bolsa 1kg", "Etiqueta Bolsa 1/2kg", "Tapa Frasco 1kg (plástico)", "Tapa Frasco 1kg (vidrio)", "Tapa Frasco 1/2kg (plástico)", "Tapa Frasco 1/2kg (vidrio)" }));
        getContentPane().add(cbxInsumo);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2);

        txtCantidadInsumo.setBackground(new java.awt.Color(255, 204, 51));
        txtCantidadInsumo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtCantidadInsumo.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCantidadInsumo);

        btnAñadir.setBackground(new java.awt.Color(255, 255, 255));
        btnAñadir.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(0, 0, 0));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAñadir);

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String tipoInsumo = cbxInsumo.getSelectedItem().toString();
        
        if(tipoInsumo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Uno o más campos vacíos, por favor rellene todo para continuar.");
        } else{
            try{
                int cant = Integer.parseInt(txtCantidadInsumo.getText());
                if (cant <= 0) {
                    JOptionPane.showMessageDialog(this, "La cantidad debe ser un número positivo.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
                    return;
                } else{
                    this.cantidad = cant;
                    this.tipoInsumo = tipoInsumo;
                    dispose();
                }
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Valor no válido en el campo 'Cantidad'", "Error de entrada", JOptionPane.ERROR_MESSAGE);
                txtCantidadInsumo.setText("");
                txtCantidadInsumo.requestFocus();
            }
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DatosInsumo dialog = new DatosInsumo(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbxInsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCantidadInsumo;
    // End of variables declaration//GEN-END:variables
}
