/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rokefeli.ui;

/**
 *
 * @author ricar
 */
public class DatosMPGenerica extends javax.swing.JDialog {

    /**
     * Creates new form DatosMPGenerica
     */
    public DatosMPGenerica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Descripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        Cantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        FechaIngreso = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        Descripcion.setBackground(new java.awt.Color(255, 255, 255));
        Descripcion.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(0, 0, 0));
        Descripcion.setText("Descripción:");
        getContentPane().add(Descripcion);

        txtDescripcion.setBackground(new java.awt.Color(255, 204, 51));
        txtDescripcion.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtDescripcion);

        Cantidad.setBackground(new java.awt.Color(255, 255, 255));
        Cantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(0, 0, 0));
        Cantidad.setText("Cantidad:");
        getContentPane().add(Cantidad);

        txtCantidad.setBackground(new java.awt.Color(255, 204, 51));
        txtCantidad.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCantidad);

        FechaIngreso.setBackground(new java.awt.Color(255, 255, 255));
        FechaIngreso.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        FechaIngreso.setForeground(new java.awt.Color(0, 0, 0));
        FechaIngreso.setText("Fecha de Ingreso:");
        getContentPane().add(FechaIngreso);

        txtFechaIngreso.setBackground(new java.awt.Color(255, 204, 51));
        txtFechaIngreso.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtFechaIngreso.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtFechaIngreso);

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar);

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosMPGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosMPGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosMPGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosMPGenerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DatosMPGenerica dialog = new DatosMPGenerica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel FechaIngreso;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFechaIngreso;
    // End of variables declaration//GEN-END:variables
}
