package rokefeli.ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import rokefeli.logic.GestorInventario;
import rokefeli.model.MateriaPrima;
import javax.swing.JPanel;
import javax.swing.JComboBox;
import javax.swing.JLabel;

public class InterfazRokefeli extends javax.swing.JFrame {

    GestorInventario gestor = new GestorInventario();
    private javax.swing.table.DefaultTableModel modeloTablaMateriaPrima;
    private javax.swing.table.DefaultTableModel modeloTablaInsumos;
    private javax.swing.table.DefaultTableModel modeloTablaProductosFinales;
    private javax.swing.table.DefaultTableModel modeloTablaRegistroMateriaPrima;
    private javax.swing.table.DefaultTableModel modeloTablaRegistroInsumos;
    private javax.swing.table.DefaultTableModel modeloTablaRegistroProductoFinal;
    private javax.swing.table.DefaultTableModel modeloTablaRegistroVentas;
    private String ultimoRegistroCargado = "";

    public InterfazRokefeli() {
        initComponents();
        setSize(930, 560);
        setLocationRelativeTo(null);
        gestor.cargarInventario();
        gestor.inicializarInsumosPorDefecto();
        
        String[] nombresColumnasMateriaPrima = {"Descripción", "ID Lote", "Floración", "Origen", "Fecha de Ingreso", "Cantidad (kg)", "Estado"};
        modeloTablaMateriaPrima = new javax.swing.table.DefaultTableModel(new Object[][]{}, nombresColumnasMateriaPrima){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tablaMateriaPrima.setModel(modeloTablaMateriaPrima);
        gestor.mostrarMateriaPrima(modeloTablaMateriaPrima, true);
        
        String[] nombresColumnasInsumos = {"Código", "Descripción", "Unidades Actuales", "Unidades Mínimas"};
        modeloTablaInsumos = new javax.swing.table.DefaultTableModel(new Object[][]{}, nombresColumnasInsumos){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tablaInsumos.setModel(modeloTablaInsumos);
        gestor.mostrarInsumos(modeloTablaInsumos);
        
        String[] nombresColumnasProductosFinales = {"SKU", "Descripción", "Lote de Origen", "Precio de Venta", "Unidades Actuales", 
            "Unidades Mínimas"};
        modeloTablaProductosFinales = new javax.swing.table.DefaultTableModel(new Object[][]{}, nombresColumnasProductosFinales){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tablaProductosFinales.setModel(modeloTablaProductosFinales);
        gestor.mostrarProductosFinales(modeloTablaProductosFinales);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                gestor.guardarInventario();
            }
        });
        
        String[] nombresColumnasRegistroMP = {"Fecha", "Movimiento", "ID Lote", "Cantidad (Kg)", "Floración", "Origen", "Estado"};
        modeloTablaRegistroMateriaPrima = new javax.swing.table.DefaultTableModel(new Object[][]{}, nombresColumnasMateriaPrima){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        String[] nombresColumnasRegistroI = {"Fecha", "Movimiento", "Código", "Descripción", "Cantidad"};
        modeloTablaRegistroInsumos = new javax.swing.table.DefaultTableModel(new Object[][]{}, nombresColumnasMateriaPrima){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        String[] nombresColumnasRegistroPF = {"Fecha", "Movimiento", "SKU", "Descripción", "Lote Asociado", "Cantidad"};
        modeloTablaRegistroProductoFinal = new javax.swing.table.DefaultTableModel(new Object[][]{}, nombresColumnasMateriaPrima){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
    }

    // Método auxiliar para parsear fechas de los JTextField
    private LocalDate parseDate(String dateStr, String fieldName) {
        if (dateStr == null || dateStr.trim().isEmpty()) {
            return null;
        }
        try {
            return LocalDate.parse(dateStr.trim());
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha '" + fieldName + "' inválido (AAAA-MM-DD).", "Error de Fecha", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnIngresarLoteMiel = new javax.swing.JButton();
        btnMostrarMateriaPrimaTotal = new javax.swing.JButton();
        btnTransformarMateriaPrima = new javax.swing.JButton();
        btnBuscarMateriaPrima = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnMostrarMateriaPrimaHistorico = new javax.swing.JButton();
        btnIngresarGenerica = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaMateriaPrima = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnIngresarInsumo = new javax.swing.JButton();
        btnBuscarInsumo = new javax.swing.JButton();
        btnMostrarInsumosTotal = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaInsumos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnCrearProductoFinal = new javax.swing.JButton();
        btnBuscarProductoFinal = new javax.swing.JButton();
        btnMostrarProductosFinales = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProductosFinales = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFechaDesde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaHasta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPalabraClave = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnLimpiarFiltros = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnRegistroMateriaPrima = new javax.swing.JButton();
        btnRegistroInsumos = new javax.swing.JButton();
        btnRegistroProductosFinales = new javax.swing.JButton();
        btnRegistroVentas = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 204, 51));
        jPanel5.setPreferredSize(new java.awt.Dimension(911, 116));

        btnIngresarLoteMiel.setBackground(new java.awt.Color(255, 255, 51));
        btnIngresarLoteMiel.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnIngresarLoteMiel.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarLoteMiel.setText("Ingresar Lote Miel");
        btnIngresarLoteMiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLoteMielActionPerformed(evt);
            }
        });

        btnMostrarMateriaPrimaTotal.setBackground(new java.awt.Color(255, 255, 51));
        btnMostrarMateriaPrimaTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnMostrarMateriaPrimaTotal.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarMateriaPrimaTotal.setText("Mostrar Total");
        btnMostrarMateriaPrimaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMateriaPrimaTotalActionPerformed(evt);
            }
        });

        btnTransformarMateriaPrima.setBackground(new java.awt.Color(255, 255, 51));
        btnTransformarMateriaPrima.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnTransformarMateriaPrima.setForeground(new java.awt.Color(0, 0, 0));
        btnTransformarMateriaPrima.setText("Transformar");
        btnTransformarMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransformarMateriaPrimaActionPerformed(evt);
            }
        });

        btnBuscarMateriaPrima.setBackground(new java.awt.Color(255, 255, 51));
        btnBuscarMateriaPrima.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnBuscarMateriaPrima.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarMateriaPrima.setText("Filtrar");
        btnBuscarMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMateriaPrimaActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rokefeli/img/processed_image (2).png"))); // NOI18N

        btnMostrarMateriaPrimaHistorico.setBackground(new java.awt.Color(255, 255, 51));
        btnMostrarMateriaPrimaHistorico.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnMostrarMateriaPrimaHistorico.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarMateriaPrimaHistorico.setText("Mostrar Histórico");
        btnMostrarMateriaPrimaHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMateriaPrimaHistoricoActionPerformed(evt);
            }
        });

        btnIngresarGenerica.setBackground(new java.awt.Color(255, 255, 51));
        btnIngresarGenerica.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnIngresarGenerica.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarGenerica.setText("Ingresar Genérica");
        btnIngresarGenerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarGenericaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnMostrarMateriaPrimaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarMateriaPrimaHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnIngresarLoteMiel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresarGenerica, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTransformarMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTransformarMateriaPrima)
                            .addComponent(btnIngresarLoteMiel)
                            .addComponent(btnIngresarGenerica))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarMateriaPrimaTotal)
                            .addComponent(btnMostrarMateriaPrimaHistorico)
                            .addComponent(btnBuscarMateriaPrima))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tablaMateriaPrima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "ID Lote", "Floración", "Origen", "Fecha de Ingreso", "Cantidad (kg)", "Estado"
            }
        ));
        jScrollPane5.setViewportView(tablaMateriaPrima);
        if (tablaMateriaPrima.getColumnModel().getColumnCount() > 0) {
            tablaMateriaPrima.getColumnModel().getColumn(0).setHeaderValue("Descripción");
            tablaMateriaPrima.getColumnModel().getColumn(1).setHeaderValue("ID Lote");
            tablaMateriaPrima.getColumnModel().getColumn(2).setHeaderValue("Floración");
            tablaMateriaPrima.getColumnModel().getColumn(3).setHeaderValue("Origen");
            tablaMateriaPrima.getColumnModel().getColumn(4).setHeaderValue("Fecha de Ingreso");
            tablaMateriaPrima.getColumnModel().getColumn(5).setHeaderValue("Cantidad (kg)");
            tablaMateriaPrima.getColumnModel().getColumn(6).setHeaderValue("Estado");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Materia Prima", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 204, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(911, 116));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rokefeli/img/processed_image (2).png"))); // NOI18N

        btnIngresarInsumo.setBackground(new java.awt.Color(255, 255, 51));
        btnIngresarInsumo.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnIngresarInsumo.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarInsumo.setText("Ingresar Insumo");
        btnIngresarInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarInsumoActionPerformed(evt);
            }
        });

        btnBuscarInsumo.setBackground(new java.awt.Color(255, 255, 51));
        btnBuscarInsumo.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnBuscarInsumo.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarInsumo.setText("Búsqueda");
        btnBuscarInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInsumoActionPerformed(evt);
            }
        });

        btnMostrarInsumosTotal.setBackground(new java.awt.Color(255, 255, 51));
        btnMostrarInsumosTotal.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnMostrarInsumosTotal.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarInsumosTotal.setText("Mostrar Insumos Totales");
        btnMostrarInsumosTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInsumosTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnIngresarInsumo)
                .addGap(30, 30, 30)
                .addComponent(btnBuscarInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnMostrarInsumosTotal)
                .addGap(51, 51, 51))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarInsumosTotal)
                            .addComponent(btnIngresarInsumo)
                            .addComponent(btnBuscarInsumo))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tablaInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descripción", "Unidades", "Mínimo"
            }
        ));
        jScrollPane4.setViewportView(tablaInsumos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Insumos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 204, 51));
        jPanel8.setPreferredSize(new java.awt.Dimension(911, 116));

        btnCrearProductoFinal.setBackground(new java.awt.Color(255, 255, 51));
        btnCrearProductoFinal.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnCrearProductoFinal.setForeground(new java.awt.Color(0, 0, 0));
        btnCrearProductoFinal.setText("Crear Producto Final");
        btnCrearProductoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoFinalActionPerformed(evt);
            }
        });

        btnBuscarProductoFinal.setBackground(new java.awt.Color(255, 255, 51));
        btnBuscarProductoFinal.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnBuscarProductoFinal.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarProductoFinal.setText("Búsqueda");
        btnBuscarProductoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoFinalActionPerformed(evt);
            }
        });

        btnMostrarProductosFinales.setBackground(new java.awt.Color(255, 255, 51));
        btnMostrarProductosFinales.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnMostrarProductosFinales.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarProductosFinales.setText("Mostrar Productos");
        btnMostrarProductosFinales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProductosFinalesActionPerformed(evt);
            }
        });

        btnVenta.setBackground(new java.awt.Color(255, 255, 51));
        btnVenta.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnVenta.setText("Despacho");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rokefeli/img/processed_image (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarProductosFinales, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearProductoFinal))
                .addGap(119, 119, 119)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProductoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(btnVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProductoFinal)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnCrearProductoFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarProductosFinales)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablaProductosFinales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SKU", "Descripción", "Lote de Origen", "Precio de Venta", "Unidades"
            }
        ));
        jScrollPane3.setViewportView(tablaProductosFinales);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Productos Finales", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fecha Desde (AAAA-MM-DD):");

        txtFechaDesde.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Hasta:");

        txtFechaHasta.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Palabra Clave:");

        txtPalabraClave.setBackground(new java.awt.Color(204, 204, 204));
        txtPalabraClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalabraClaveActionPerformed(evt);
            }
        });

        btnFiltrar.setBackground(new java.awt.Color(255, 255, 51));
        btnFiltrar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnLimpiarFiltros.setBackground(new java.awt.Color(255, 255, 51));
        btnLimpiarFiltros.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnLimpiarFiltros.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiarFiltros.setText("Limpiar Filtros");
        btnLimpiarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFiltrosActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 204, 51));
        jPanel7.setPreferredSize(new java.awt.Dimension(911, 116));

        btnRegistroMateriaPrima.setBackground(new java.awt.Color(255, 255, 51));
        btnRegistroMateriaPrima.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnRegistroMateriaPrima.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistroMateriaPrima.setText("Materia Prima");
        btnRegistroMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroMateriaPrimaActionPerformed(evt);
            }
        });

        btnRegistroInsumos.setBackground(new java.awt.Color(255, 255, 51));
        btnRegistroInsumos.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnRegistroInsumos.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistroInsumos.setText("Insumos");
        btnRegistroInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroInsumosActionPerformed(evt);
            }
        });

        btnRegistroProductosFinales.setBackground(new java.awt.Color(255, 255, 51));
        btnRegistroProductosFinales.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnRegistroProductosFinales.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistroProductosFinales.setText("Productos");
        btnRegistroProductosFinales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroProductosFinalesActionPerformed(evt);
            }
        });

        btnRegistroVentas.setBackground(new java.awt.Color(255, 255, 51));
        btnRegistroVentas.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        btnRegistroVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistroVentas.setText("Despacho");
        btnRegistroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroVentasActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rokefeli/img/processed_image (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnRegistroMateriaPrima)
                .addGap(34, 34, 34)
                .addComponent(btnRegistroInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnRegistroProductosFinales)
                .addGap(35, 35, 35)
                .addComponent(btnRegistroVentas)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistroInsumos)
                            .addComponent(btnRegistroProductosFinales)
                            .addComponent(btnRegistroMateriaPrima)
                            .addComponent(btnRegistroVentas)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seleccione una opción para visualizar registros."
            }
        ));
        jScrollPane6.setViewportView(tablaRegistros);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiarFiltros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPalabraClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar)
                    .addComponent(btnLimpiarFiltros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registros", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPalabraClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalabraClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalabraClaveActionPerformed

    private void btnIngresarLoteMielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLoteMielActionPerformed
        MateriaPrima nuevoLote = gestor.ingresarLoteMiel(this);
        if (nuevoLote != null) {
            if (!gestor.repetirLote(nuevoLote.getIdLote())) {
                gestor.inventarioMateriaPrima.add(nuevoLote);
                JOptionPane.showMessageDialog(rootPane, "Agregado correctamente.");
                String tipoMov = "Entrada";
                String descripcion = nuevoLote.getFloracion() + "|" + nuevoLote.getOrigen() + "|" + nuevoLote.getEstado();
                gestor.registrarMovimientoMateriaPrima(tipoMov, nuevoLote.getFechaCompra(), nuevoLote.getIdLote(),nuevoLote.getCantKg(), descripcion);
                gestor.mostrarMateriaPrima(modeloTablaMateriaPrima, true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "El id de lote ingresado ya existe.");
            }
        } else if(nuevoLote == null){
            JOptionPane.showMessageDialog(rootPane, "Ingreso cancelado.");
        }
    }//GEN-LAST:event_btnIngresarLoteMielActionPerformed

    private void btnMostrarMateriaPrimaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMateriaPrimaTotalActionPerformed
        gestor.mostrarMateriaPrima(modeloTablaMateriaPrima, true);
    }//GEN-LAST:event_btnMostrarMateriaPrimaTotalActionPerformed

    private void btnBuscarMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMateriaPrimaActionPerformed
        String criterio = JOptionPane.showInputDialog(this, "Ingrese ID del Lote o Floración para buscar:");
        if (criterio == null || criterio.trim().isEmpty()) {
            return;
        }
        //txtaResultadosMateriaPrima.setText(gestor.buscarMateriaPrima(criterio));
    }//GEN-LAST:event_btnBuscarMateriaPrimaActionPerformed

    private void btnTransformarMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransformarMateriaPrimaActionPerformed
        String idLote = JOptionPane.showInputDialog(this, "Ingrese el ID del Lote a transformar:");
        if (idLote == null || idLote.trim().isEmpty()) {
            return;
        }
        MateriaPrima loteSeleccionado = null;
        for (MateriaPrima lote : gestor.inventarioMateriaPrima) {
            if (lote.getIdLote().equalsIgnoreCase(idLote)) {
                loteSeleccionado = lote;
                break;
            }
        }
        if (loteSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Lote no encontrado.");
            return;
        }
        String estadoActual = loteSeleccionado.getEstado();
        String[] estados = {" ", "Pasteurizada", "Lista para Envasar"};
        JComboBox<String> comboEstados = new JComboBox<>(estados);
        comboEstados.setSelectedItem(" ");
        JPanel panel = new JPanel();
        panel.add(new JLabel("Seleccione el nuevo estado:"));
        panel.add(comboEstados);
        int resultado = JOptionPane.showConfirmDialog(this, panel, "Cambiar Estado", JOptionPane.OK_CANCEL_OPTION);
        if (resultado != JOptionPane.OK_OPTION) {
            return;
        }
        String nuevoEstado = (String) comboEstados.getSelectedItem();
        if (nuevoEstado.equals(estadoActual) || nuevoEstado.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado una opción válida.");
            return;
        }
        if (nuevoEstado.equals("En Reposo") || (nuevoEstado.equals("Pasteurizada") && !estadoActual.equals("En Reposo")) || (nuevoEstado.equals("Lista para Envasar") && !estadoActual.equals("Pasteurizada"))) {
            JOptionPane.showMessageDialog(this, "ERROR: Movimiento de estado no permitido.");
            return;
        }
        gestor.transformarLote(loteSeleccionado.getIdLote(), nuevoEstado);
        JOptionPane.showMessageDialog(this, "Estado del lote actualizado a: " + nuevoEstado);
        String tipoMov = "Transformación";
        String descripcion = loteSeleccionado.getOrigen() + "|" + loteSeleccionado.getFloracion() + "|" + loteSeleccionado.getEstado();
        gestor.registrarMovimientoMateriaPrima(tipoMov, loteSeleccionado.getFechaCompra(), loteSeleccionado.getIdLote(), loteSeleccionado.getCantKg(), descripcion);
        gestor.mostrarMateriaPrima(modeloTablaMateriaPrima, true);
    }//GEN-LAST:event_btnTransformarMateriaPrimaActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        if (ultimoRegistroCargado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, primero carga un registro seleccionando una categoría.", "Acción Requerida", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String texto = txtPalabraClave.getText();
        String fechaI = txtFechaDesde.getText();
        String fechaF = txtFechaHasta.getText();

        String contenidoFiltrado = gestor.getContenidoRegistroFiltrado(ultimoRegistroCargado, texto, fechaI, fechaF);
        //txtaResultadosRegistros.setText(contenidoFiltrado);
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnLimpiarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFiltrosActionPerformed
        txtPalabraClave.setText("");
        txtFechaDesde.setText("");
        txtFechaHasta.setText("");
        if (!ultimoRegistroCargado.isEmpty()) {
            //txtaResultadosRegistros.setText(gestor.getContenidoRegistro(ultimoRegistroCargado));
        }
    }//GEN-LAST:event_btnLimpiarFiltrosActionPerformed

    private void btnRegistroMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroMateriaPrimaActionPerformed
        ultimoRegistroCargado = "Materia Prima";
        String textoBusqueda = txtPalabraClave.getText().trim();
        LocalDate fechaInicio = parseDate(txtFechaDesde.getText(), "Desde");
        LocalDate fechaFin = parseDate(txtFechaHasta.getText(), "Hasta");

        if ((txtFechaDesde.getText().trim().isEmpty() || fechaInicio != null)
                && (txtFechaHasta.getText().trim().isEmpty() || fechaFin != null)) {

            String registros = gestor.filtrarRegistros(
                    gestor.getNombreRegistroMateriaPrima(), // <--- ¡Aquí se usa el método para el nombre del archivo!
                    textoBusqueda.isEmpty() ? null : textoBusqueda,
                    fechaInicio,
                    fechaFin
            );
            //txtaResultadosRegistros.setText(registros);
        }
    }//GEN-LAST:event_btnRegistroMateriaPrimaActionPerformed

    private void btnRegistroInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroInsumosActionPerformed
        ultimoRegistroCargado = "Insumos";
        String textoBusqueda = txtPalabraClave.getText().trim();
        LocalDate fechaInicio = parseDate(txtFechaDesde.getText(), "Desde");
        LocalDate fechaFin = parseDate(txtFechaHasta.getText(), "Hasta");

        if ((txtFechaDesde.getText().trim().isEmpty() || fechaInicio != null)
                && (txtFechaHasta.getText().trim().isEmpty() || fechaFin != null)) {

            String registros = gestor.filtrarRegistros(
                    gestor.getNombreRegistroInsumos(),
                    textoBusqueda.isEmpty() ? null : textoBusqueda,
                    fechaInicio,
                    fechaFin
            );
            //txtaResultadosRegistros.setText(registros);
        }
    }//GEN-LAST:event_btnRegistroInsumosActionPerformed

    private void btnRegistroProductosFinalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroProductosFinalesActionPerformed
        ultimoRegistroCargado = "Productos Finales";
        String textoBusqueda = txtPalabraClave.getText().trim();
        LocalDate fechaInicio = parseDate(txtFechaDesde.getText(), "Desde");
        LocalDate fechaFin = parseDate(txtFechaHasta.getText(), "Hasta");

        if ((txtFechaDesde.getText().trim().isEmpty() || fechaInicio != null)
                && (txtFechaHasta.getText().trim().isEmpty() || fechaFin != null)) {

            String registros = gestor.filtrarRegistros(
                    gestor.getNombreRegistroProductosFinales(),
                    textoBusqueda.isEmpty() ? null : textoBusqueda,
                    fechaInicio,
                    fechaFin
            );
            //txtaResultadosRegistros.setText(registros);
        }
    }//GEN-LAST:event_btnRegistroProductosFinalesActionPerformed

    private void btnRegistroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroVentasActionPerformed
        ultimoRegistroCargado = "Despachos";
        btnLimpiarFiltrosActionPerformed(null);
    }//GEN-LAST:event_btnRegistroVentasActionPerformed

    private void btnBuscarInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInsumoActionPerformed
        String codigo = JOptionPane.showInputDialog(this, "Ingrese el código del insumo a buscar:");
        if (codigo == null || codigo.trim().isEmpty()) {
            return;
        }
        //txtaResultadosInsumos.setText(gestor.buscarInsumoPorCodigo(codigo));
    }//GEN-LAST:event_btnBuscarInsumoActionPerformed

    private void btnMostrarInsumosTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInsumosTotalActionPerformed
        gestor.mostrarInsumos(modeloTablaInsumos);
    }//GEN-LAST:event_btnMostrarInsumosTotalActionPerformed

    private void btnIngresarInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarInsumoActionPerformed
        DatosInsumo dialog = new DatosInsumo(this);
        dialog.setVisible(true);

        if (dialog.getTipoInsumo() != null && dialog.getCantidad() > 0) {
            String tipoInsumo = dialog.getTipoInsumo(); // Obtiene la descripción del insumo
            int cantidad = dialog.getCantidad(); // Obtiene la cantidad a ingresar/retirar
            String codigo = null;

            String mensaje = gestor.aniadirStockInsumo(codigo, tipoInsumo, cantidad);
            JOptionPane.showMessageDialog(this, mensaje);

            // Actualiza la visualización de los insumos en tu interfaz
            gestor.mostrarInsumos(modeloTablaInsumos);
        }
    }//GEN-LAST:event_btnIngresarInsumoActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // Obtener la lista de productos disponibles del gestor principal
        String[] productosDisponibles = gestor.getDescripcionesProductosParaVenta();

        // Verificar si hay productos antes de mostrar el diálogo
        if (productosDisponibles == null || productosDisponibles.length == 0) {
            JOptionPane.showMessageDialog(this,
                "No hay productos con stock disponibles para el despacho.",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
            return; // No abrir el diálogo
        }

        // Pasar la lista de productos al constructor de DatosVenta
        DatosVenta dialog = new DatosVenta(this, productosDisponibles);
        dialog.setVisible(true);

        if (dialog.isConfirmado()) {
            String productoSeleccionado = dialog.getProductoSeleccionado();
            int cantidad = dialog.getCantidad();
            String comprador = dialog.getComprador();

            String resultadoVenta = gestor.procesarVenta(productoSeleccionado, cantidad, comprador);
            JOptionPane.showMessageDialog(this, resultadoVenta);

            //txtaResultadosProductosFinales.setText(gestor.mostrarProductosFinales());
            gestor.guardarInventario(); // Guardar cambios después de la venta
            
            gestor.mostrarProductosFinales(modeloTablaProductosFinales);
        }
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnMostrarProductosFinalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProductosFinalesActionPerformed
        gestor.mostrarProductosFinales(modeloTablaProductosFinales);
    }//GEN-LAST:event_btnMostrarProductosFinalesActionPerformed

    private void btnBuscarProductoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoFinalActionPerformed
        String criterio = JOptionPane.showInputDialog(this, "Ingrese descripción del producto a buscar:");
        if (criterio != null && !criterio.trim().isEmpty()) {
            //txtaResultadosProductosFinales.setText(gestor.buscarProductoFinal(criterio));
        }
    }//GEN-LAST:event_btnBuscarProductoFinalActionPerformed

    private void btnCrearProductoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoFinalActionPerformed
        // 1. Obtener la lista de IDs de lotes listos para envasar
        String[] idsLotesListos = gestor.getIdsLotesListosParaEnvasar();

        // 2. Verificar si hay lotes disponibles. Si no, informar al usuario.
        if (idsLotesListos == null || idsLotesListos.length == 0) {
            JOptionPane.showMessageDialog(this, // 'this' se refiere a la instancia de InterfazRokefeli
                "No hay lotes de miel en estado 'Lista para Envasar'.\n"
                + "Por favor, transforme un lote primero.",
                "Acción Requerida",
                JOptionPane.INFORMATION_MESSAGE);
            return; // Salir del método ya que no hay lotes para mostrar
        }

        // 3. Crear una instancia de DatosProductoFinal, pasándole la ventana padre y los IDs de los lotes
        DatosProductoFinal dialog = new DatosProductoFinal(this, idsLotesListos); // 'this' como Frame parent

        // 4. Hacer visible el diálogo
        dialog.setVisible(true);

        // 5. Una vez que el diálogo se cierra, verificar si el usuario confirmó la operación
        if (dialog.isConfirmado()) {
            try {
                String idLoteSeleccionado = dialog.getIdLoteSeleccionado();
                String tipoProducto = dialog.getTipoProductoSeleccionado();
                int cantidadEnvases = dialog.getCantidad();

                // Llamar al método del GestorInventario para crear el producto final
                String resultado = gestor.crearProductoFinal(idLoteSeleccionado, tipoProducto, cantidadEnvases);
                JOptionPane.showMessageDialog(this, resultado, "Producto Final Creado", JOptionPane.INFORMATION_MESSAGE);

                // Actualizar la vista de productos finales en la InterfazRokefeli y de las demás tablas
                gestor.mostrarProductosFinales(modeloTablaProductosFinales);
                gestor.mostrarMateriaPrima(modeloTablaMateriaPrima, true);
                gestor.mostrarInsumos(modeloTablaInsumos);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error al procesar la cantidad. Asegúrese de que sea un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al crear el producto final: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // Para depuración
            }
        }
    }//GEN-LAST:event_btnCrearProductoFinalActionPerformed

    private void btnMostrarMateriaPrimaHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMateriaPrimaHistoricoActionPerformed
        gestor.mostrarMateriaPrima(modeloTablaMateriaPrima, false);
    }//GEN-LAST:event_btnMostrarMateriaPrimaHistoricoActionPerformed

    private void btnIngresarGenericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarGenericaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarGenericaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRokefeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRokefeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRokefeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRokefeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // 1. Crear y mostrar el diálogo de login
                LoginDialog loginDialog = new LoginDialog(null, true); // Pasa 'null' como padre si aún no hay un JFrame principal
                loginDialog.setVisible(true); // Esto hace que el diálogo sea modal y espere aquí hasta que se cierre

                // 2. Después de que el diálogo se cierra, verifica si la autenticación fue exitosa
                if (loginDialog.isAutenticacionExitosa()) {
                    // Si es exitosa, crea y muestra el JFrame principal
                    InterfazRokefeli frame = new InterfazRokefeli();
                    frame.setVisible(true);
                } else {
                    // Si la autenticación falló o fue cancelada, muestra un mensaje y cierra la aplicación
                    JOptionPane.showMessageDialog(null, "Autenticación cancelada. La aplicación se cerrará.", "Cerrar", JOptionPane.INFORMATION_MESSAGE);
                    System.exit(0); // Termina la aplicación si el login no fue exitoso
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarInsumo;
    private javax.swing.JButton btnBuscarMateriaPrima;
    private javax.swing.JButton btnBuscarProductoFinal;
    private javax.swing.JButton btnCrearProductoFinal;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnIngresarGenerica;
    private javax.swing.JButton btnIngresarInsumo;
    private javax.swing.JButton btnIngresarLoteMiel;
    private javax.swing.JButton btnLimpiarFiltros;
    private javax.swing.JButton btnMostrarInsumosTotal;
    private javax.swing.JButton btnMostrarMateriaPrimaHistorico;
    private javax.swing.JButton btnMostrarMateriaPrimaTotal;
    private javax.swing.JButton btnMostrarProductosFinales;
    private javax.swing.JButton btnRegistroInsumos;
    private javax.swing.JButton btnRegistroMateriaPrima;
    private javax.swing.JButton btnRegistroProductosFinales;
    private javax.swing.JButton btnRegistroVentas;
    private javax.swing.JButton btnTransformarMateriaPrima;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private javax.swing.JTable tablaInsumos;
    private javax.swing.JTable tablaMateriaPrima;
    private javax.swing.JTable tablaProductosFinales;
    private javax.swing.JTable tablaRegistros;
    private javax.swing.JTextField txtFechaDesde;
    private javax.swing.JTextField txtFechaHasta;
    private javax.swing.JTextField txtPalabraClave;
    // End of variables declaration//GEN-END:variables
}
